<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="FB-133" name="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest" tests="10" failures="2" timestamp="23 Apr 2019 11:20:10 GMT" time="647.401" errors="0">
  <testcase name="UpdateAccount" time="71.178" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error; Region Name in Excel And DB dose NOT matchIn test Case With ID of expected [true] but found [false],
	code expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error; Region Name in Excel And DB dose NOT matchIn test Case With ID of expected [true] but found [false],
code expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at fawry.sofAutomation.testsActions.accounts.UpdateAccountTest.UpdateAccount(UpdateAccountTest.java:146)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UpdateAccount -->
  <testcase name="UpdateAccount" time="72.250" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest"/>
  <testcase name="UpdateAccount" time="71.271" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest"/>
  <testcase name="UpdateAccount" time="70.070" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest"/>
  <testcase name="UpdateAccount" time="70.290" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	loca expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
loca expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at fawry.sofAutomation.testsActions.accounts.UpdateAccountTest.UpdateAccount(UpdateAccountTest.java:146)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UpdateAccount -->
  <testcase name="UpdateAccount" time="70.858" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest"/>
  <testcase name="UpdateAccount" time="70.620" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest"/>
  <testcase name="UpdateAccount" time="70.065" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest"/>
  <testcase name="UpdateAccount" time="70.960" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest"/>
  <testcase name="UpdateAccount" time="9.839" classname="fawry.sofAutomation.testsActions.accounts.UpdateAccountTest"/>
</testsuite> <!-- fawry.sofAutomation.testsActions.accounts.UpdateAccountTest -->
