<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="FB-133" name="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest" tests="11" failures="1" timestamp="07 May 2019 10:48:11 GMT" time="1183.309" errors="1">
  <testcase name="SearchTerminal" time="199.471" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at fawry.sofAutomation.testsActions.accounts.SearchTerminalTest.SearchTerminal(SearchTerminalTest.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- SearchTerminal -->
  <testcase name="SearchTerminal" time="66.383" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
  <testcase name="SearchTerminal" time="328.211" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
  <testcase name="SearchTerminal" time="28.495" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
  <testcase name="SearchTerminal" time="58.882" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
  <testcase name="SearchTerminal" time="5.824" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
  <testcase name="SearchTerminal" time="16.164" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
  <testcase name="SearchTerminal" time="292.310" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error; accounts shown on web table and in db does NOT matchIn test Case With ID of expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error; accounts shown on web table and in db does NOT matchIn test Case With ID of expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at fawry.sofAutomation.testsActions.accounts.SearchTerminalTest.SearchTerminal(SearchTerminalTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SearchTerminal -->
  <testcase name="SearchTerminal" time="42.239" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
  <testcase name="SearchTerminal" time="103.195" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
  <testcase name="SearchTerminal" time="42.135" classname="fawry.sofAutomation.testsActions.accounts.SearchTerminalTest"/>
</testsuite> <!-- fawry.sofAutomation.testsActions.accounts.SearchTerminalTest -->
